// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL9eyl5xlgPGdTuxHBN-5ggjO_xYwILkk',
    appId: '1:503736540594:web:5da80b48a0f4a89f7e18ab',
    messagingSenderId: '503736540594',
    projectId: 'cinewall-6221d',
    authDomain: 'cinewall-6221d.firebaseapp.com',
    storageBucket: 'cinewall-6221d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrC3IGRIxT5pEFqJcKTYkNA69lfJ8iMRM',
    appId: '1:503736540594:android:4b21992af04d5cb47e18ab',
    messagingSenderId: '503736540594',
    projectId: 'cinewall-6221d',
    storageBucket: 'cinewall-6221d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMb7kLjLCRcA_43qu1GY7Mh5irKeQu6Go',
    appId: '1:503736540594:ios:a669ccaf2067dee47e18ab',
    messagingSenderId: '503736540594',
    projectId: 'cinewall-6221d',
    storageBucket: 'cinewall-6221d.firebasestorage.app',
    iosBundleId: 'com.example.cinemawall',
  );
}
